[download] improve error message
while give

```
2014-08-30 12:24 INFO     download      bt-chat.com     Downloading: Bering.Sea.Gold.Under.the.Ice.S03E02.480p.HDTV.x264-mSD
2014-08-30 12:24 WARNING  download      bt-chat.com     RequestException [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed, while downloading https://torcache.net/torrent/C28D6A86369E095B7D3509D4C86C0BC09286995B.torrent
```

 instead of

 ```
 2014-08-30 12:30 INFO     download      bt-chat.com     Downloading: Bering.Sea.Gold.Under.the.Ice.S03E02.480p.HDTV.x264-mSD
2014-08-30 12:30 WARNING  download      bt-chat.com     RequestException [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```